#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="$REPO_DIR/scripts/git-identities.conf"
EXAMPLE="$REPO_DIR/scripts/git-identities.conf.example"
CONF_D="$HOME/.gitconfig.d"
MANAGED="$CONF_D/managed.gitconfig" # regenerated every run; holds the includeIf rules

# All commits (and tags) are signed everywhere. gpg.sh sets these too; asserting
# here keeps signing on even if this script is run on its own.
git config --global commit.gpgsign true
git config --global tag.gpgsign true

if [ ! -f "$CONF" ]; then
  echo "No git identities file at $CONF — skipping per-org identities."
  echo "To enable them:  cp \"$EXAMPLE\" \"$CONF\"  and fill it in."
  exit 0
fi

mkdir -p "$CONF_D"

# ~/.gitconfig must pull in the managed file exactly once.
if ! git config --global --get-all include.path 2>/dev/null | grep -qxF "$MANAGED"; then
  git config --global --add include.path "$MANAGED"
fi

# Start each run from a clean slate: wipe previously generated files.
rm -f "$CONF_D"/id-*.gitconfig
{
  echo "# Generated by my-workplace/scripts/git-identity.sh — do not edit by hand."
} > "$MANAGED"

trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; s="${s%"${s##*[![:space:]]}"}"; printf '%s' "$s"; }
slug() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9._-' '-'; }

emit_include() { # $1 = remote-url glob, $2 = identity file
  {
    printf '[includeIf "hasconfig:remote.*.url:%s"]\n' "$1"
    printf '\tpath = %s\n' "$2"
  } >> "$MANAGED"
}

write_identity() { # $1 = file, $2 = name, $3 = email
  {
    echo "# Generated by my-workplace/scripts/git-identity.sh"
    echo "[user]"
    printf '\tname = %s\n' "$2"
    printf '\temail = %s\n' "$3"
  } > "$1"
}

while IFS='|' read -r platform org name email || [ -n "$platform" ]; do
  platform="$(trim "${platform:-}")"
  [ -z "$platform" ] && continue
  case "$platform" in \#*) continue ;; esac

  org="$(trim "${org:-}")"
  name="$(trim "${name:-}")"
  email="$(trim "${email:-}")"
  if [ -z "$org" ] || [ -z "$name" ] || [ -z "$email" ]; then
    echo "Skipping malformed line: $platform|$org|$name|$email" >&2
    continue
  fi

  id_file="$CONF_D/id-$(slug "$platform")-$(slug "$org").gitconfig"
  write_identity "$id_file" "$name" "$email"

  case "$platform" in
    github)
      emit_include "https://github.com/$org/**" "$id_file"
      emit_include "git@github.com:$org/**" "$id_file"
      emit_include "ssh://git@github.com/$org/**" "$id_file"
      ;;
    azure | ado | azuredevops)
      emit_include "https://dev.azure.com/$org/**" "$id_file"
      emit_include "https://$org@dev.azure.com/$org/**" "$id_file"
      emit_include "git@ssh.dev.azure.com:v3/$org/**" "$id_file"
      emit_include "ssh://git@ssh.dev.azure.com/v3/$org/**" "$id_file"
      emit_include "https://$org.visualstudio.com/**" "$id_file"
      emit_include "https://$org@$org.visualstudio.com/**" "$id_file"
      ;;
    url)
      # org holds a raw remote-URL glob (e.g. https://git.example.com/team/**)
      emit_include "$org" "$id_file"
      ;;
    *)
      echo "Unknown platform '$platform' (use github, azure, or url) — skipping." >&2
      rm -f "$id_file"
      ;;
  esac

  echo "Configured $platform/$org -> $name <$email>"
done < "$CONF"

echo "Done. Per-org identities live in $CONF_D (local, untracked)."
echo "Verify in a repo with:  git -C <repo> config user.email"
